#!/usr/bin/env node
const fs = require('fs');

const packStr = fs.readFileSync('./package.json', 'utf-8');
const pack = JSON.parse(packStr);

pack.version = process.argv[2];

const output = JSON.stringify(pack, null, 2);
fs.writeFileSync('./package.json', output);
